package ucloud

/*
const apiTpl = `
// Code generated by apibase. DO NOT EDIT.

package {{.Pkg}}

import (
	"context"

	"git.ucloudadmin.com/usec-spd/apibase/action/base"
)


type {{.Name}}Server interface {
	{{range .Actions}}
		// {{.Name}} {{.Description}}
		{{.Name}}(ctx context.Context, request *{{.Name}}Request) (*{{.Name}}Response, error)
	{{- end}}
}

{{range .Models}}
	// {{.Name}} {{.Description}}
	type {{.Name}} struct{
		{{with .Params}}{{range .}}{{.Text}}
		{{end}}{{end}}
	}
{{- end}}



{{range .Actions}}
	type {{.Name}}Request struct{
		base.Request
		{{.BaseRequest}}
		{{with .Request}}{{range .}}{{.Text}}
		{{end}}{{end}}
	}

	type {{.Name}}Response struct{
		base.Response
		{{with .Response}}{{range .}}{{.Text}}
		{{end}}{{end}}
	}
{{- end}}

type {{.Name}}Service struct {

}

{{with $api := . }}
	{{range .Actions}}
		// {{.Name}} {{.Description}}
		func (s *{{$api.Name}}Service) {{.Name}}(ctx context.Context, in *{{.Name}}Request) (*{{.Name}}Response, error) {
			response := &{{.Name}}Response{}
			return response, nil
		}
	{{- end}}
{{- end}}
`
*/

const modelTpl = `
package controllers

{{range .Models}}
	// {{.Name}} {{.Description}}
	type {{.Name}} struct{
		{{with .Params}}{{range .}}{{.Text}}
		{{end}}{{end}}
	}
{{- end}}

`

const actionControllerTpl = `
package controllers

import (
    ac "git.ucloudadmin.com/usec-spd/apibase/controllers"
)

{{$Action := .Name}}

type {{$Action}}Request struct{
    {{.BaseRequest}}
    {{with .Request}}{{range .}}{{.Text}}
	{{end}}{{end}}
}

{{with .Response}}
type {{$Action}}Response struct{
    ac.APIResponse
    {{range .}}{{.Text}}
    {{end}}
}

func (resp {{$Action}}Response)SetAction(action string) ac.IApiResponse{
    resp.Action = action
    return resp
}
{{end}}


// {{$Action}} {{.Description}}
func (req *{{$Action}}Request){{$Action}}()interface{}{
    return nil
}

func init(){
    {{if .Response}}ac.ActionFuncRegister("{{$Action}}",nil, "{{.Description}}",new({{$Action}}Request), new({{$Action}}Response)){{else}}ac.ActionFuncRegister("{{$Action}}",nil, "{{.Description}}",new({{$Action}}Request)){{end}}
}
`
