FROM alpine:latest

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN apk --no-cache upgrade && apk --no-cache add ca-certificates && apk add tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone

COPY  bin/{{.Name}} /go/{{.Name}}

WORKDIR /go

CMD ["/go/{{.Name}}"]
